# Generated by Django 3.2 on 2022-07-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
