# Generated by Django 3.2 on 2022-07-09 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='friends',
            field=models.IntegerField(default=0),
        ),
    ]
